/**
 * Generates the typed surface of the library from `data/api.json`
 * (produced by `npm run scrape`):
 *
 *   src/generated/meta.ts   – runtime metadata (validation, listMethods(), …)
 *   src/generated/types.ts  – interfaces for every module / method
 *   docs/METHODS.md         – compact human readable reference of every method
 *   documentation.md        – full docs: index, signatures, implementations, examples
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildPath, isCommunityParam, isTimestampParam, resolveSegments } from '../src/core/params';
import type { SDSApiReference, SDSFieldMeta, SDSMethodMeta, SDSParamMeta } from '../src/meta-types';

const root = fileURLToPath(new URL('..', import.meta.url));

const BANNER = `/* eslint-disable */
/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Generated by \`npm run generate\` from the SDS API Reference.
 * Re-run \`npm run scrape && npm run generate\` to refresh it.
 */`;

/** Repository of this package (linked from every generated document). */
const REPO_URL = 'https://github.com/faisalamin9696/sds';
/** Human readable repository link text. */
const REPO_NAME = 'github.com/faisalamin9696/sds';

let sourceBase = 'https://sds0.steemworld.org';

/* ------------------------------------------------------------------ */
/* naming helpers                                                      */
/* ------------------------------------------------------------------ */

const RESERVED = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do',
  'else', 'enum', 'export', 'extends', 'false', 'finally', 'for', 'function', 'if', 'implements',
  'import', 'in', 'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private', 'protected',
  'public', 'return', 'static', 'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof', 'var',
  'void', 'while', 'with', 'yield', 'await',
]);

const isValidIdentifier = (name: string): boolean => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);

/** Property name inside an interface (`condenser_api.get_ticker` → quoted). */
const propertyName = (name: string): string =>
  isValidIdentifier(name) && !RESERVED.has(name) ? name : JSON.stringify(name);

/** Positional parameter name (must be a legal identifier that is not `callback`). */
function positionalName(name: string, index: number): string {
  if (!isValidIdentifier(name)) return `arg${index}`;
  if (RESERVED.has(name)) return `${name}$`;
  if (name === 'callback' || name === 'done') return `${name}$`;
  return name;
}

/** `getOpsInBlock` → `GetOpsInBlock`, `condenser_api.get_ticker` → `CondenserApiGetTicker`. */
function pascal(name: string): string {
  const joined = name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  return /^[0-9]/.test(joined) ? `_${joined}` : joined;
}

function allowedList(values: string[] | undefined, max = 6): string {
  if (!values?.length) return '';
  const shown = values.slice(0, max).join(' | ');
  return values.length > max ? `${shown} | … (${values.length} values)` : shown;
}

/** Callback parameter name (must not collide with a route parameter). */
const callbackNameOf = (meta: SDSMethodMeta): string =>
  meta.params.some((param) => param.name === 'callback') ? 'done' : 'callback';

/** Object style arguments interface of a method (unique per module). */
const argsNameOf = (moduleKey: string, method: SDSMethodMeta): string =>
  `${pascal(moduleKey)}${pascal(method.name)}Args`;

/* ------------------------------------------------------------------ */
/* type mapping                                                        */
/* ------------------------------------------------------------------ */

function tsType(param: SDSParamMeta): string {
  const type = param.type.trim().toLowerCase();

  if (type === 'int' || type === 'float' || type === 'number') {
    // Timestamp parameters accept any date form — the client converts it to
    // unix seconds before the request is sent (see `isTimestampParam`).
    return type === 'int' && isTimestampParam(param) ? 'number | string | Date' : 'number';
  }
  if (type === 'bool' || type === 'boolean') return 'boolean';
  if (type.startsWith('hex_string')) return 'string';
  if (type === 'account_name') return 'string';

  if (type === 'fixed_value') {
    if (param.allowedValues?.length) {
      return param.allowedValues.map((value) => JSON.stringify(value)).join(' | ');
    }
    return 'string';
  }

  if (type === 'fixed_csv') {
    // The value lists are long (up to ~80 entries), so a plain string/list is
    // used here — the documented values are kept in the JSDoc and in the
    // metadata (`describeMethod()`).
    return 'string | string[]';
  }

  if (type === 'account_name_csv') return 'string | string[]';
  if (type === 'int_csv') return 'string | number | Array<string | number>';
  if (type.startsWith('json_object')) return 'SDSJsonObject | string';
  if (type.startsWith('json_array')) return 'SDSJsonArray | string';
  if (type.startsWith('json')) return 'unknown';
  return 'string';
}

function resultTsType(result: string | undefined): string {
  switch ((result ?? '').trim().toLowerCase()) {
    case 'json object':
      return 'SDSJsonObject';
    case 'json array':
      return 'SDSJsonArray';
    case 'integer':
      return 'number';
    case 'string':
      return 'string';
    case 'boolean':
      return 'boolean';
    default:
      return 'any';
  }
}

function paramDoc(param: SDSParamMeta): string {
  const parts = [param.type];
  if (isCommunityParam(param)) parts.push(`hive community id, e.g. \`hive-160125\``);
  if (isTimestampParam(param))
    parts.push('timestamp — accepts `Date`, date string or unix seconds (12+ digit numbers are read as ms)');
  if (param.default !== undefined) parts.push(`default \`${param.default}\``);
  if (param.min !== undefined && param.max !== undefined) parts.push(`${param.min}…${param.max}`);
  else if (param.min !== undefined) parts.push(`min ${param.min}`);
  else if (param.max !== undefined) parts.push(`max ${param.max}`);
  const allowed = allowedList(param.allowedValues, 4);
  if (allowed) parts.push(`one of: ${allowed}`);
  if (param.fields?.length) parts.push(`${param.fields.length} documented fields`);
  return parts.join(' · ');
}

function rangeText(param: SDSParamMeta): string {
  if (param.min !== undefined && param.max !== undefined) return `${param.min} – ${param.max}`;
  if (param.min !== undefined) return `≥ ${param.min}`;
  if (param.max !== undefined) return `≤ ${param.max}`;
  return '';
}

/** Type cell of a parameter table — flags hive community ids and timestamps. */
function typeCell(param: SDSParamMeta): string {
  if (isCommunityParam(param)) return `${param.type} (e.g. \`${COMMUNITY_ID_SAMPLE}\`)`;
  if (isTimestampParam(param)) return `${param.type} (Date / date string / seconds)`;
  return param.type;
}

/* ------------------------------------------------------------------ */
/* signature generation                                                 */
/* ------------------------------------------------------------------ */

function methodDoc(meta: SDSMethodMeta): string[] {
  const callback = callbackNameOf(meta);
  const lines: string[] = ['/**'];
  const description = meta.description ?? 'No description available.';
  for (const line of description.split('\n')) lines.push(` * ${line.replace(/\*\//g, '*\\/')}`);
  lines.push(' *');
  lines.push(` * @param ${callback} node style callback \`(error, result) => void\``);
  if (meta.params.length) {
    lines.push(' *');
    lines.push(' * Parameters (positional, in route order):');
    for (const param of meta.params) {
      lines.push(
        ` * - \`${param.name}\` (${param.optional ? 'optional' : 'required'}) — ${paramDoc(param)}`,
      );
    }
  }
  lines.push(' *');
  lines.push(` * @see ${sourceBase}/describeMethod/${meta.module}.${meta.name}`);
  lines.push(' */');
  return lines;
}

function signatureLines(meta: SDSMethodMeta, argsName: string): string[] {
  const prop = propertyName(meta.name);
  const callback = callbackNameOf(meta);
  const result = resultTsType(meta.result);
  const params = meta.params;
  const allOptional = params.every((param) => param.optional);
  const lines: string[] = [];
  const push = (signature: string): void => {
    lines.push(`  ${signature}`);
  };

  if (params.length === 0) {
    push(`${prop}<T = ${result}>(${callback}: Callback<T>): Promise<void>;`);
    push(`${prop}<T = ${result}>(): Promise<T>;`);
    return lines;
  }

  if (allOptional) {
    push(`${prop}<T = ${result}>(${callback}: Callback<T>): Promise<void>;`);
  }

  push(`/** Object style with callback. */`);
  push(`${prop}<T = ${result}>(args: ${argsName}, ${callback}: Callback<T>): Promise<void>;`);
  push(`/** Object style, promise. */`);
  push(`${prop}<T = ${result}>(args: ${argsName}): Promise<T>;`);

  // TS forbids a required parameter after an optional one, so the callback
  // variant declares optional parameters as `type | undefined` instead of `?`.
  const withCallback = params
    .map((param, index) => {
      const name = positionalName(param.name, index);
      const type = tsType(param);
      return param.optional ? `${name}: ${type} | undefined` : `${name}: ${type}`;
    })
    .join(', ');
  push(`${prop}<T = ${result}>(${withCallback}, ${callback}: Callback<T>): Promise<void>;`);

  const lastRequired = params.reduce((last, param, index) => (param.optional ? last : index), -1);
  const plain = params
    .map((param, index) => {
      const name = positionalName(param.name, index);
      const type = tsType(param);
      if (param.optional && index > lastRequired) return `${name}?: ${type}`;
      return `${name}: ${type}${param.optional ? ' | undefined' : ''}`;
    })
    .join(', ');
  push(`${prop}<T = ${result}>(${plain}): Promise<T>;`);

  return lines;
}

function argsInterface(method: SDSMethodMeta, interfaceName: string): string[] {
  const lines: string[] = [
    `/** Object style arguments of \`${method.module}.${method.name}\`. */`,
    `export interface ${interfaceName} {`,
  ];
  for (const param of method.params) {
    lines.push(`  /** ${paramDoc(param)} */`);
    lines.push(`  ${propertyName(param.name)}${param.optional ? '?' : ''}: ${tsType(param)};`);
  }
  lines.push('}');
  return lines;
}

/* ------------------------------------------------------------------ */
/* documentation examples                                              */
/* ------------------------------------------------------------------ */

/**
 * Sample community id used in generated examples — every community parameter
 * is a `hive-` prefixed hivemind account (verified against all 3112 live
 * communities; bare ids/titles/accounts answer with empty results).
 */
const COMMUNITY_ID_SAMPLE = 'hive-160125';

/** Property access, dotted names use bracket notation (`sds.x["get.ticker"]`). */
function accessor(name: string): string {
  return isValidIdentifier(name) && !RESERVED.has(name)
    ? `.${name}`
    : `[${JSON.stringify(name)}]`;
}

function coerceScalar(type: string, raw: string): unknown {
  const normalized = type.trim().toLowerCase();
  if (normalized === 'int' || normalized === 'float' || normalized === 'number') {
    const number = Number(raw);
    return Number.isFinite(number) ? number : raw;
  }
  if (normalized === 'bool' || normalized === 'boolean') return raw === 'true' || raw === '1';
  if (normalized.startsWith('json')) {
    try {
      return JSON.parse(raw);
    } catch {
      return raw;
    }
  }
  return raw;
}

/** Sample value for a documented field of a structured parameter. */
function sampleField(field: SDSFieldMeta): unknown {
  if (field.default !== undefined && field.default !== 'null') {
    return coerceScalar(field.type, field.default);
  }
  const type = field.type.trim().toLowerCase();
  if (isTimestampParam(field)) {
    // Keep `fromTime` before `toTime` so generated ranges stay sane.
    const leaf = (field.name.split('.').pop() ?? field.name).toLowerCase();
    return timestampSample(leaf.startsWith('to') ? 1 : 0);
  }
  if (type === 'int' || type === 'float' || type === 'number') return 10;
  if (type === 'bool' || type === 'boolean') return true;
  if (type === 'account_name') return isCommunityParam(field) ? COMMUNITY_ID_SAMPLE : 'alice';
  if (type === 'fixed_value') return field.allowedValues?.[0] ?? 'value';
  if (type.startsWith('json_object')) return {};
  if (type.startsWith('json_array')) return [];
  if (field.fields?.length) return sampleFields(field.fields);
  return 'example';
}

/** Builds a nested sample object from the documented (dotted) field paths. */
function sampleFields(fields: SDSFieldMeta[]): Record<string, unknown> {
  const root: Record<string, unknown> = {};
  for (const field of fields) {
    const parts = field.name.split('.');
    let node = root;
    for (const part of parts.slice(0, -1)) {
      if (typeof node[part] !== 'object' || node[part] === null) node[part] = {};
      node = node[part] as Record<string, unknown>;
    }
    node[parts[parts.length - 1]] = sampleField(field);
  }
  return root;
}

/**
 * Sample value of a structured parameter built from its documented fields.
 *
 * Documented paths are prefixed with the parameter name (`query.type` for the
 * `query` parameter); the prefix is dropped because the JSON payload itself
 * only contains the inner structure (`{ "type": … }`).
 */
function sampleJson(param: SDSParamMeta): Record<string, unknown> {
  const prefix = `${param.name}.`;
  const fields = (param.fields ?? []).map((field) =>
    field.name.startsWith(prefix) ? { ...field, name: field.name.slice(prefix.length) } : field,
  );
  return sampleFields(fields);
}

/**
 * Fixed base day of generated timestamp examples — deterministic docs.
 * `2020-09-13` is unix `1599961600`; `1600000000` (used in prose) is
 * `2020-09-13T12:26:40Z`.
 */
const TIMESTAMP_SAMPLE_DAY = Date.UTC(2020, 8, 13);

/** Sample timestamp as a date string, `days` after the base day. */
const timestampSample = (days: number): string =>
  new Date(TIMESTAMP_SAMPLE_DAY + days * 86_400_000).toISOString().slice(0, 10);

/** Plausible sample value for a parameter (documented default when available). */
function sampleValue(param: SDSParamMeta, index: number): unknown {
  const type = param.type.trim().toLowerCase();

  if (param.default !== undefined && param.default !== 'null') {
    return coerceScalar(param.type, param.default);
  }
  if (type === 'account_name') return isCommunityParam(param) ? COMMUNITY_ID_SAMPLE : 'alice';
  if (type.startsWith('hex_string')) return '0'.repeat(40);
  if (isTimestampParam(param)) return timestampSample(index);
  if (type === 'int' || type === 'float' || type === 'number') {
    let value = 10 + index;
    if (param.min !== undefined && value < param.min) value = param.min;
    if (param.max !== undefined && value > param.max) value = param.max;
    return value;
  }
  if (type === 'bool' || type === 'boolean') return true;
  if (type === 'fixed_value') return param.allowedValues?.[0] ?? 'value';
  if (type === 'fixed_csv') return param.allowedValues?.slice(0, 2).join(',') ?? 'value';
  if (type === 'int_csv') return '1,2';
  if (type === 'account_name_csv') return 'alice,bob';
  if (type.endsWith('_csv') || type === 'csv') return 'value1,value2';
  if (type.startsWith('json')) return sampleJson(param);
  return 'example';
}

/** Sample values for every parameter of a method (positional, route order). */
function sampleArgs(meta: SDSMethodMeta): unknown[] {
  return meta.params.map((param, index) => sampleValue(param, index));
}

/** TypeScript literal of a sample value (`{ fromTime: 0 }`, `'alice'`, …). */
function tsLiteral(value: unknown): string {
  if (typeof value === 'string') return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return `[${value.map(tsLiteral).join(', ')}]`;
  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (!entries.length) return '{}';
    const body = entries
      .map(([key, entry]) => `${isValidIdentifier(key) && !RESERVED.has(key) ? key : JSON.stringify(key)}: ${tsLiteral(entry)}`)
      .join(', ');
    return `{ ${body} }`;
  }
  return 'null';
}

/** Example request URL for a method (documented defaults filled in). */
function exampleUrl(meta: SDSMethodMeta): string | undefined {
  try {
    const segments = resolveSegments(meta, sampleArgs(meta), { validate: true }).map((segment) =>
      encodeURIComponent(segment),
    );
    return `${sourceBase}${buildPath(meta.path, segments)}`;
  } catch {
    return undefined;
  }
}

/** Compact overload signatures (JSDoc comment lines stripped, dedented). */
function docSignature(meta: SDSMethodMeta, argsName: string): string[] {
  return signatureLines(meta, argsName)
    .filter((line) => !line.trim().startsWith('/**'))
    .map((line) => line.trim());
}

/* ------------------------------------------------------------------ */
/* file generators                                                     */
/* ------------------------------------------------------------------ */

function generateMeta(reference: SDSApiReference): string {
  return `${BANNER}
import type { SDSModuleMeta } from '../meta-types';

/** Instance the metadata was scraped from. */
export const SDS_REFERENCE_SOURCE = ${JSON.stringify(reference.source)};

/** Version of the SDS API reference the metadata was scraped from. */
export const SDS_REFERENCE_VERSION = ${JSON.stringify(reference.version)};

/** Date of the scrape. */
export const SDS_REFERENCE_DATE = ${JSON.stringify(reference.scrapedAt)};

/** All SDS modules with their methods, in reference order. */
export const SDS_MODULES: SDSModuleMeta[] = ${JSON.stringify(reference.modules, null, 2)};
`;
}

function generateTypes(reference: SDSApiReference): string {
  const out: string[] = [
    BANNER,
    '',
    "import type { Callback } from '../types';",
    '',
    '/** Result payload of methods documented as `JSON Object`. */',
    'export type SDSJsonObject = Record<string, any>;',
    '',
    '/** Result payload of methods documented as `JSON Array`. */',
    'export type SDSJsonArray = any[];',
  ];

  const moduleMap: string[] = [];
  const moduleKeys: string[] = [];
  const namespaces: string[] = [];

  for (const module of reference.modules) {
    const interfaceName = `${pascal(module.key)}Api`;
    const seenMethods = new Set<string>();
    const seenArgs = new Set<string>();
    const members: string[] = [];

    for (const method of module.methods) {
      if (seenMethods.has(method.name)) {
        throw new Error(`Duplicate method ${module.id}.${method.name}`);
      }
      seenMethods.add(method.name);

      if (method.params.length) {
        const argsName = argsNameOf(module.key, method);
        if (seenArgs.has(argsName)) {
          throw new Error(`Duplicate arguments interface ${argsName}`);
        }
        seenArgs.add(argsName);
        out.push('');
        out.push(...argsInterface(method, argsName));
      }

      members.push('');
      members.push(...methodDoc(method).map((line) => `  ${line}`));
      members.push(...signatureLines(method, argsNameOf(module.key, method)));
    }

    out.push('');
    out.push(`/** Module \`${module.id}\` (group: ${module.group}). */`);
    out.push(`export interface ${interfaceName} {`);
    out.push(...members);
    out.push('}');
    out.push('');

    moduleMap.push(`  ${JSON.stringify(module.id)}: ${interfaceName};`);
    moduleKeys.push(`  ${JSON.stringify(module.id)}: ${JSON.stringify(module.key)};`);
    namespaces.push(`  /** \`${module.id}\` */`, `  ${module.key}: ${interfaceName};`);
  }

  out.push('/** Map of SDS module id → module interface. */');
  out.push('export interface SDSModuleMap {');
  out.push(...moduleMap);
  out.push('}');
  out.push('');
  out.push('/** Map of SDS module id → namespace key on the client. */');
  out.push('export interface SDSModuleKeys {');
  out.push(...moduleKeys);
  out.push('}');
  out.push('');
  out.push('/** Module namespaces exposed by the client (`sds.chain`, `sds.posts`, …). */');
  out.push('export interface SDSModules {');
  out.push(...namespaces);
  out.push('}');
  out.push('');

  return out.join('\n');
}

function generateDocs(reference: SDSApiReference): string {
  const methodCount = reference.modules.reduce((sum, module) => sum + module.methods.length, 0);
  const out: string[] = [];

  out.push('# SDS Method Reference');
  out.push('');
  out.push(
    `Generated from [\`${reference.source}\`](${reference.source}) — reference version \`${reference.version}\`, ${reference.modules.length} modules, ${methodCount} methods. ` +
      `Source: [${REPO_NAME}](${REPO_URL}).`,
  );
  out.push('');
  out.push('| Module | Namespace | Group | Methods |');
  out.push('| --- | --- | --- | --- |');
  for (const module of reference.modules) {
    out.push(
      `| [\`${module.id}\`](#${module.id}) | \`sds.${module.key}\` | ${module.group} | ${module.methods.length} |`,
    );
  }
  out.push('');

  for (const module of reference.modules) {
    out.push('---');
    out.push('');
    out.push(`## \`${module.id}\``);
    out.push('');
    out.push(
      `Namespace: \`sds.${module.key}\` · Group: ${module.group} · ${module.methods.length} methods`,
    );
    out.push('');

    for (const method of module.methods) {
      out.push(`### \`sds.${module.key}.${method.name}()\``);
      out.push('');
      out.push(method.description || '_No description available._');
      out.push('');
      out.push(`- Route: \`${method.path}\``);
      if (method.result) out.push(`- Result: ${method.result}`);
      if (method.maxLimit !== undefined) out.push(`- Max. limit: ${method.maxLimit}`);
      if (method.example) out.push(`- Example: \`${method.example}\``);
      out.push('');

      if (method.params.length) {
        out.push('| Parameter | Type | Required | Default | Range | Allowed values |');
        out.push('| --- | --- | --- | --- | --- | --- |');
        for (const param of method.params) {
          out.push(
            `| \`${param.name}\` | ${typeCell(param)} | ${param.optional ? 'no' : 'yes'} | ${
              param.default !== undefined ? `\`${param.default}\`` : '—'
            } | ${rangeText(param) || '—'} | ${
              param.allowedValues?.length ? allowedList(param.allowedValues, 8) : '—'
            } |`,
          );
        }
        out.push('');
      } else {
        out.push('_No parameters._');
        out.push('');
      }
    }
  }

  out.push('');
  return out.join('\n');
}

/* ------------------------------------------------------------------ */
/* documentation.md generation                                         */
/* ------------------------------------------------------------------ */

/**
 * GitHub style anchor for a heading (used by the method index links).
 *
 * Matches GitHub's slugger: lowercase, drop everything but word characters,
 * hyphens and spaces, then turn *each* space into a hyphen (spaces are not
 * collapsed, so `Initialization & instances` → `initialization--instances`).
 */
function anchor(text: string): string {
  return text
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/[^\w\- ]+/g, '')
    .trim()
    .replace(/ /g, '-');
}

/** Paragraphs of a description (blank line separated), indented for lists. */
function descriptionLines(description: string | undefined, indent = ''): string[] {
  if (!description) return [`${indent}_No description available._`];
  return description
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.replace(/\s*\n\s*/g, ' ').trim())
    .filter(Boolean)
    .flatMap((paragraph, index) => (index === 0 ? [`${indent}${paragraph}`] : ['', `${indent}${paragraph}`]));
}

/** The generated implementation signature block of a method. */
function implementationBlock(meta: SDSMethodMeta, argsName: string): string[] {
  const lines: string[] = ['```ts'];
  if (meta.params.length) {
    lines.push(`interface ${argsName} {`);
    for (const param of meta.params) {
      lines.push(`  ${propertyName(param.name)}${param.optional ? '?' : ''}: ${tsType(param)};  // ${paramDoc(param)}`);
    }
    lines.push('}');
    lines.push('');
  }
  lines.push(...docSignature(meta, argsName));
  lines.push('```');
  return lines;
}

/** Runnable promise/callback/object style examples of a call. */
function usageExamples(meta: SDSMethodMeta, moduleKey: string): string[] {
  const call = `sds.${moduleKey}${accessor(meta.name)}`;
  const args = sampleArgs(meta);
  const positional = args.map(tsLiteral).join(', ');
  const objectStyle =
    meta.params.length > 0
      ? `{ ${meta.params.map((param, index) => `${propertyName(param.name)}: ${tsLiteral(args[index])}`).join(', ')} }`
      : undefined;

  const lines: string[] = ['```ts'];

  // Promise style (positional).
  if (meta.params.length === 0) {
    lines.push(`const result = await ${call}();`);
  } else {
    lines.push(`const result = await ${call}(${positional});`);
  }

  // Object style, shown as a commented alternative (same scope, no redeclaration).
  if (objectStyle && objectStyle !== positional) {
    lines.push(`// …or object style:`);
    lines.push(`// const result = await ${call}(${objectStyle});`);
  }

  // Callback style.
  if (meta.params.length === 0) {
    lines.push(`${call}((error, result) => {`);
  } else {
    lines.push(`${call}(${positional}, (error, result) => {`);
  }
  lines.push('  if (error) return console.error(error.code, error.message);');
  lines.push('  console.log(result);');
  lines.push('});');

  // Generic entry point.
  lines.push('');
  if (meta.params.length === 0) {
    lines.push(`await sds.call('${meta.module}', '${meta.name}');`);
  } else {
    lines.push(`await sds.call('${meta.module}', '${meta.name}', ${positional ? `[${positional}]` : '[]'});`);
  }
  lines.push('```');
  return lines;
}

function generateDocumentation(reference: SDSApiReference): string {
  const methodCount = reference.modules.reduce((sum, module) => sum + module.methods.length, 0);
  const out: string[] = [];

  /* ---------------------------------------------------------------- */
  /* front matter                                                      */
  /* ---------------------------------------------------------------- */

  out.push('# `@steempro/sds` — Full Documentation');
  out.push('');
  out.push(
    `Generated from [\`${reference.source}\`](${reference.source}) — reference version \`${reference.version}\`, ` +
      `${reference.modules.length} modules, ${methodCount} methods, scraped ${reference.scrapedAt}. ` +
      `Source: [${REPO_NAME}](${REPO_URL}).`,
  );
  out.push('');
  out.push(
    '> This file is generated by `npm run generate`. ' +
      'A compact table-only reference lives in [`docs/METHODS.md`](docs/METHODS.md), ' +
      'the prose guide in [`README.md`](README.md).',
  );
  out.push('');

  out.push('## Table of contents');
  out.push('');
  out.push('1. [Installation](#installation)');
  out.push('2. [Initialization & instances](#initialization--instances)');
  out.push('3. [Calling methods](#calling-methods)');
  out.push('4. [Mapping responses with `mapSds`](#mapping-responses-with-mapsds)');
  out.push('5. [Error handling](#error-handling)');
  out.push('6. [Introspection](#introspection)');
  out.push(`7. [Method index](#method-index) (${methodCount} methods)`);
  out.push('8. [API reference](#api-reference)');
  out.push('');

  out.push('## Installation');
  out.push('');
  out.push('```bash');
  out.push('npm i @steempro/sds');
  out.push('```');
  out.push('');
  out.push('```ts');
  out.push("import { SDS } from '@steempro/sds';       // ESM / TypeScript");
  out.push("const { SDS } = require('@steempro/sds');  // CommonJS");
  out.push('```');
  out.push('');
  out.push('Requires Node 18+ (or Deno / Bun / a browser — anything with `fetch`), or pass your own `{ fetch }`.');
  out.push('');

  out.push('## Initialization & instances');
  out.push('');
  out.push('| Option | Default | Description |');
  out.push('| --- | --- | --- |');
  out.push('| `instance` | `"sds0"` | Bundled name (`sds`, `sds0`, `sds1`), a registered name, or a full URL |');
  out.push('| `baseUrl` | – | Full base URL (takes precedence over `instance`) |');
  out.push('| `instances` | `{}` | Extra `{ name: url }` pairs for this client only |');
  out.push('| `timeout` | `30000` | Request timeout in ms (`0` disables it) |');
  out.push('| `retries` | `2` | Retries for network / timeout / 5xx / 429 failures |');
  out.push('| `retryDelay` | `300` | Base delay of the exponential backoff in ms |');
  out.push('| `headers` | `{}` | Extra headers sent with every request |');
  out.push('| `fetch` | `globalThis.fetch` | Custom fetch implementation |');
  out.push('| `validate` | `true` | Client side parameter validation (type / range / allow list) |');
  out.push('| `encode` | `true` | URL-encode path segments |');
  out.push('| `onRequest` / `onResponse` | – | Logging / tracing hooks |');
  out.push('');
  out.push('```ts');
  out.push("import { SDS, registerInstance, listInstances, DEFAULT_SDS_INSTANCES } from '@steempro/sds';");
  out.push('');
  out.push("const sds0 = new SDS();                                  // https://sds0.steemworld.org");
  out.push("const sds1 = new SDS({ instance: 'sds1' });              // https://sds1.steemworld.org");
  out.push("const custom = new SDS({ baseUrl: 'https://my-sds.example.org' });");
  out.push('');
  out.push('// Your own instance — per client …');
  out.push("const sds9 = new SDS({ instance: 'sds9', instances: { sds9: 'https://sds9.example.org' } });");
  out.push('// … or process wide:');
  out.push("registerInstance('sds9', 'https://sds9.example.org');");
  out.push("const again = new SDS({ instance: 'sds9' });");
  out.push('');
  out.push('console.log(DEFAULT_SDS_INSTANCES, listInstances());');
  out.push('```');
  out.push('');

  out.push('## Calling methods');
  out.push('');
  out.push('Every method supports **positional (route order)** arguments, a **single object** keyed by');
  out.push('parameter name, and an optional trailing **node-style callback**:');
  out.push('');
  out.push('```ts');
  out.push('// 1. Promise, positional (order = route order)');
  out.push("await sds.chain.getAccountNamesByPrefix('ste', 50);");
  out.push('');
  out.push('// 2. Promise, object style');
  out.push("await sds.chain.getAccountNamesByPrefix({ prefix: 'ste', limit: 50 });");
  out.push('');
  out.push('// 3. Callback (either style) — (error, result) => void');
  out.push("sds.chain.getAccountNamesByPrefix('ste', 50, (error, names) => {");
  out.push('  if (error) return console.error(error.code, error.message);');
  out.push('  console.log(names);');
  out.push('});');
  out.push('');
  out.push('// 4. Generic entry point (works for methods missing from the bundle too)');
  out.push("await sds.call('chain_api', 'getAccountNames', [10, 0], { timeout: 5000 });");
  out.push('');
  out.push('// 5. Raw GET, envelope unwrapped for you');
  out.push("await sds.request('/chain_api/getConfig');");
  out.push('```');
  out.push('');
  out.push('Rules the argument resolver follows:');
  out.push('');
  out.push('- Trailing optional parameters are **omitted** — SDS applies their documented defaults.');
  out.push('- Skipped middle parameters are filled with the documented default, or the literal');
  out.push('  `null` placeholder SDS accepts (e.g. `observer`).');
  out.push('- Routes with two parameters in one segment become `from-to` (e.g. `getBlocksInRange(1, 5)` → `/1-5`).');
  out.push('- CSV parameters accept an array or a comma separated string and are joined with `,`.');
  out.push('- Community parameters take a **hive community id** — always `hive-` prefixed');
  out.push('  (e.g. `hive-160125`). Bare ids, titles and regular accounts are rejected up front');
  out.push('  (SDS would silently answer with empty data); disable with `validate: false`.');
  out.push('- Timestamp parameters (`fromTime`, `toTime`, `blockTime`, `…date`) accept **any date');
  out.push('  form** — a `Date`, `"2020-09-13"`, `"2020-09-13 12:30:00"`, `"2020/09/13"`,');
  out.push('  `"2020-09-13T12:30:00+02:00"` or unix seconds — and are converted to unix **seconds**');
  out.push('  (the unit SDS expects) before the request is sent; zone-less strings are treated as');
  out.push('  UTC and 12+ digit numbers are read as milliseconds. Values that cannot be parsed');
  out.push('  throw an `SDSValidationError` listing the accepted formats instead of silently');
  out.push('  returning empty or "now" data.');
  out.push('- Client side validation (`validate: true`) rejects bad types, out-of-range values and');
  out.push('  values outside an allow list before anything is sent.');
  out.push('');

  out.push('## Mapping responses with `mapSds`');
  out.push('');
  out.push('Many SDS list/search methods return a **column oriented table** instead of objects:');
  out.push('');
  out.push('```json');
  out.push('{');
  out.push('  "cols": { "link_id": 0, "author": 6, "permlink": 7 },');
  out.push('  "rows": [[114136936, 0, 69.305, 0, "", "", "alice", "hello"]]');
  out.push('}');
  out.push('```');
  out.push('');
  out.push('`mapSds()` converts that into plain row objects — and passes every other payload');
  out.push('(plain JSON, arrays, raw `{ code, result }` envelopes) through unchanged:');
  out.push('');
  out.push('```ts');
  out.push("import { mapSds, isSDSTable } from '@steempro/sds';");
  out.push('');
  out.push("const feed = await sds.feeds.getActivePostsByCreated({ limit: 1 });");
  out.push('const rows = mapSds(feed);');
  out.push('// [ { link_id: 114136936, author: \'alice\', permlink: \'hello\', … }, … ]');
  out.push('');
  out.push('// …or straight from the promise:');
  out.push('const rows2 = await sds.feeds');
  out.push("  .getActivePostsByCreated({ limit: 1 })");
  out.push('  .then(mapSds);');
  out.push('');
  out.push('// Narrow first if the payload type is unknown:');
  out.push('const payload: unknown = await sds.request(\'/feeds_api/getActivePostsByTrending\');');
  out.push('const rows3 = isSDSTable(payload) ? mapSds(payload) : payload;');
  out.push('```');
  out.push('');
  out.push('Implementation:');
  out.push('');
  out.push('```ts');
  out.push('export function mapSds(data: SDSTable): SDSRow[];');
  out.push('export function mapSds<T = any>(data: unknown): T;');
  out.push('');
  out.push('export function mapSds(data: unknown): unknown {');
  out.push('  const payload = unwrapEnvelope(data);          // { code, result } → result');
  out.push('  if (!isSDSTable(payload)) return payload;      // not a table → unchanged');
  out.push('');
  out.push('  const cols = payload.cols;                     // { name: index } or [name, …]');
  out.push('  const rows = payload.rows ?? [];');
  out.push('  const names = Array.isArray(cols) ? cols : Object.keys(cols);');
  out.push('');
  out.push('  return rows.map((row) => {');
  out.push('    if (Array.isArray(row)) {');
  out.push('      const out = {};');
  out.push('      names.forEach((name, position) => {');
  out.push('        out[name] = row[Array.isArray(cols) ? position : cols[name]];');
  out.push('      });');
  out.push('      return out;                               // positional row → keyed object');
  out.push('    }');
  out.push('    if (row && typeof row === "object") return { ...row };');
  out.push('    return { [names[0]]: row };                 // scalar row of a 1-column table');
  out.push('  });');
  out.push('}');
  out.push('```');
  out.push('');
  out.push('Why this version differs from the naive `Object.keys(cols).map((k, i) => …)` version:');
  out.push('');
  out.push('- **Index lookup, not position**: values are taken at `cols[name]`, so an unordered');
  out.push('  `cols` map (or a subset of columns) maps correctly.');
  out.push('- **Array `cols`** (`["a", "b"]`) is supported as well as the object form.');
  out.push('- **Already keyed rows** are shallow-copied instead of being zipped against `cols`.');
  out.push('- **Scalar rows** of a single-column table become `{ name: value }` instead of `undefined`.');
  out.push('- **Empty table** (`cols` without `rows`) yields `[]`, never `undefined`.');
  out.push('- **Raw envelopes** (`{ code: 0, result: { cols, rows } }` from `sds.request()` of a');
  out.push('  non-unwrapped payload) are unwrapped first; error envelopes pass through.');
  out.push('- **Typed overloads**: a known `SDSTable` input gives `SDSRow[]`, anything else keeps');
  out.push('  its own type (`mapSds<T>(x)`), so plain JSON is never lied about as rows.');
  out.push('');

  out.push('## Error handling');
  out.push('');
  out.push('Every failure is an `SDSError` subclass with a stable `code` plus `module`, `method`, `url`:');
  out.push('');
  out.push('| Class | `code` | When |');
  out.push('| --- | --- | --- |');
  out.push('| `SDSValidationError` | `ERR_SDS_VALIDATION` | Parameter failed type / range / allow-list validation |');
  out.push('| `SDSArgumentError` | `ERR_SDS_ARGUMENT` | Unknown method, instance or parameter; wrong arity |');
  out.push('| `SDSNetworkError` | `ERR_SDS_NETWORK` | Request never reached SDS (DNS, CORS, offline) |');
  out.push('| `SDSTimeoutError` | `ERR_SDS_TIMEOUT` | Request exceeded `timeout` (`error.timeout`) |');
  out.push('| `SDSAbortError` | `ERR_SDS_ABORT` | Cancelled through an `AbortSignal` |');
  out.push('| `SDSHttpError` | `ERR_SDS_HTTP` | Non-success HTTP status (`error.status`, `error.body`) |');
  out.push('| `SDSResponseError` | `ERR_SDS_RESPONSE` | HTTP 200 but not the expected JSON envelope |');
  out.push('| `SDSApiError` | `ERR_SDS_API` | Application error `{ code: -1, error }` (`error.apiCode`) |');
  out.push('');
  out.push('```ts');
  out.push("import { SDSApiError, isSDSError } from '@steempro/sds';");
  out.push('');
  out.push('try {');
  out.push("  await sds.posts.getPost('alice', 'missing');");
  out.push('} catch (error) {');
  out.push('  if (error instanceof SDSApiError) console.log(error.apiCode, error.errorMessage);');
  out.push('  if (isSDSError(error)) console.log(error.toJSON());  // log / serialize safely');
  out.push('}');
  out.push('');
  out.push('// Callback style delivers the same errors instead of throwing:');
  out.push("sds.posts.getPost('alice', 'missing', (error, post) => {");
  out.push('  if (error) return console.error(error.code, error.message);');
  out.push('  console.log(post);');
  out.push('});');
  out.push('```');
  out.push('');
  out.push('Retries: network failures, timeouts, HTTP 5xx and 429 are retried with exponential');
  out.push('backoff (`retries`, `retryDelay`, overridable per call). Application errors are never retried.');
  out.push('');

  out.push('## Introspection');
  out.push('');
  out.push('```ts');
  out.push('sds.listModules();                                 // all modules');
  out.push("sds.listMethods('chain_api');                      // methods of one module");
  out.push("sds.describeMethod('chain_api.getAccountNames');   // path, params, defaults, result");
  out.push("sds.hasMethod('posts_api', 'getPost');            // true");
  out.push("sds.module('chain_api');                          // → sds.chain namespace");
  out.push('sds.referenceVersion;                             // bundled reference version');
  out.push('');
  out.push("import { listModules, listMethods, findMethod, API_REFERENCE } from '@steempro/sds';");
  out.push('```');
  out.push('');

  /* ---------------------------------------------------------------- */
  /* method index                                                      */
  /* ---------------------------------------------------------------- */

  out.push('## Method index');
  out.push('');
  out.push(`All ${methodCount} methods, grouped by module. Every entry links to its documentation below.`);
  out.push('');

  let globalIndex = 0;
  for (const [modulePosition, module] of reference.modules.entries()) {
    const moduleNumber = modulePosition + 1;
    out.push(`${moduleNumber}. **\`${module.id}\`** (\`sds.${module.key}\`, ${module.methods.length} methods)`);
    out.push('');
    const entries: string[] = [];
    for (const [methodPosition, method] of module.methods.entries()) {
      globalIndex++;
      const index = `${moduleNumber}.${methodPosition + 1}`;
      const title = `${index} \`sds.${module.key}.${method.name}\``;
      entries.push(`- [${index} \`sds.${module.key}.${method.name}\`](#${anchor(title)}) — global #${globalIndex}`);
    }
    out.push(...entries);
    out.push('');
  }

  /* ---------------------------------------------------------------- */
  /* api reference                                                     */
  /* ---------------------------------------------------------------- */

  out.push('## API reference');
  out.push('');
  out.push(
    'Each entry shows the documentation, the route, the parameters, the generated TypeScript');
  out.push('implementation (overloads) and runnable examples (promise, object style, callback, generic `call`).');
  out.push('');

  globalIndex = 0;
  for (const [modulePosition, module] of reference.modules.entries()) {
    const moduleNumber = modulePosition + 1;

    out.push('---');
    out.push('');
    out.push(`### ${moduleNumber}. \`${module.id}\``);
    out.push('');
    out.push(
      `Namespace: \`sds.${module.key}\` · Group: ${module.group} · ${module.methods.length} methods`,
    );
    out.push('');

    for (const [methodPosition, method] of module.methods.entries()) {
      globalIndex++;
      const index = `${moduleNumber}.${methodPosition + 1}`;
      const argsName = argsNameOf(module.key, method);
      const title = `${index} \`sds.${module.key}.${method.name}\``;

      out.push(`#### ${title}`);
      out.push('');
      out.push(`Global index: **#${globalIndex}** · Anchor: [\`#${anchor(title)}\`](#${anchor(title)})`);
      out.push('');
      out.push(...descriptionLines(method.description));
      out.push('');
      out.push(`- Route: \`${method.path}\``);
      if (method.result) out.push(`- Result: ${method.result}`);
      if (method.maxLimit !== undefined) out.push(`- Max. limit: ${method.maxLimit}`);
      if (method.section) out.push(`- Section: ${method.section}`);
      if (method.example) out.push(`- Reference example: \`${method.example}\``);
      const url = exampleUrl(method);
      if (url) out.push(`- Example request: \`${url}\``);
      out.push('');

      out.push('**Parameters**');
      out.push('');
      if (method.params.length) {
        out.push('| # | Name | Type | Required | Default | Range | Allowed values |');
        out.push('| --- | --- | --- | --- | --- | --- | --- |');
        method.params.forEach((param, paramIndex) => {
          out.push(
            `| ${paramIndex + 1} | \`${param.name}\` | ${typeCell(param)} | ${param.optional ? 'no' : 'yes'} | ${
              param.default !== undefined ? `\`${param.default}\`` : '—'
            } | ${rangeText(param) || '—'} | ${
              param.allowedValues?.length ? allowedList(param.allowedValues, 8) : '—'
            } |`,
          );
        });
        out.push('');
      } else {
        out.push('_No parameters._');
        out.push('');
      }

      out.push('**Implementation**');
      out.push('');
      out.push(...implementationBlock(method, argsName));
      out.push('');
      out.push('**Examples**');
      out.push('');
      out.push(...usageExamples(method, module.key));
      out.push('');
    }
  }

  out.push('---');
  out.push('');
  out.push(
    `Generated from [\`${reference.source}\`](${reference.source}) — reference version \`${reference.version}\`. ` +
      `Source: [${REPO_NAME}](${REPO_URL}).`,
  );
  out.push('');
  return out.join('\n');
}

/* ------------------------------------------------------------------ */
/* main                                                                */
/* ------------------------------------------------------------------ */

async function main(): Promise<void> {
  const reference: SDSApiReference = JSON.parse(
    await readFile(path.join(root, 'data', 'api.json'), 'utf8'),
  );
  sourceBase = reference.source;

  await mkdir(path.join(root, 'src', 'generated'), { recursive: true });
  await mkdir(path.join(root, 'docs'), { recursive: true });

  await writeFile(path.join(root, 'src', 'generated', 'meta.ts'), generateMeta(reference), 'utf8');
  await writeFile(path.join(root, 'src', 'generated', 'types.ts'), generateTypes(reference), 'utf8');
  await writeFile(path.join(root, 'docs', 'METHODS.md'), generateDocs(reference), 'utf8');
  await writeFile(path.join(root, 'documentation.md'), generateDocumentation(reference), 'utf8');

  const methodCount = reference.modules.reduce((sum, module) => sum + module.methods.length, 0);
  console.log(
    `Generated src/generated/{meta,types}.ts, docs/METHODS.md and documentation.md — ` +
      `${reference.modules.length} modules, ${methodCount} methods (reference v${reference.version})`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
